name: Docker - Runner


on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
    paths:
      - docker/Dockerfile
      - docker/docker-entrypoint.sh
      - .github/workflows/docker-runner.yml
  workflow_dispatch:


jobs:
  build-and-push:
    name: Build and Push
    uses: logos-storage/github-actions/.github/workflows/docker-reusable.yml@master
    with:
      docker_file: docker/Dockerfile
      dockerhub_repo: logosstorage/cs-codex-dist-tests
      tag_latest: true
    secrets: inherit
